### ISSUE TITLE
possible R CMD check issue

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleSCR#2]
In running reverse dependency check for `nimble`, I got this R CMD check note:

```
Namespace in Imports field not imported from: ‘methods’
  All declared Imports should be used.
```

**Comment by Cyril-Milleret** [comment]
I have checked and updated all @import arguments of the R functions, but the note still occurs during package building. @danielturek, do you know what could help fixing this issue?

**Comment by Cyril-Milleret** [comment]
I have checked and updated all import arguments of the R functions, but the note still occurs during package building. @danielturek, do you know what could help fixing this issue?

**Comment by danielturek** [comment]
@paciorek @Cyril-Milleret No, it's not apparent to me what `R CMD check` is flagging as from `methods`.  Without including `Imports: methods`, we get the note:
```
  package 'methods' is used but not declared
```
Being that this hasn't caused an issue for CRAN, @paciorek do you expect that would change?  It's not apparent to me what functions it thinks are being used from `methods`.

**Comment by paciorek** [comment]
I will take a look in coming days.

**Comment by paciorek** [comment]
I think we need to add

```
import(methods)
```

to `NAMESPACE`.

**Comment by Cyril-Milleret** [comment]
adding 
```
 #' @import methods
```
to the `getLocalObjects.R` function allowed to write 
```
import(methods)
```
to `NAMESPACE` which fixed the issue. However, I am not sure it should be added to `getLocalObjects.R`. But this is a R function and hopefully won't cause any further issues.

**Comment by paciorek** [comment]
I think it is fine to put `#'@import methods` anywhere in any of the R code files.

**Comment by danielturek** [comment]
@paciorek @Cyril-Milleret Looks good, thank you both.
