### ISSUE TITLE
distributions incorrectly registered as discrete

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleSCR#3]
`dbernppAC` (and probably others) are registered as discrete but don't look to actually be so.

This is interfering with a new error trap we want to introduce into nimble to prevent assignment of `RW_block` sampler to discrete nodes. The interference comes because the point process vignette fails to compile during reverse dependency checking for nimble because with the error trap in place, `RW_block` cannot be assigned to `sxy`. 

@danielturek  and possible others, I think the simple solution is to not tag `dbernppAC` (and any other analogous cases) as `discrete=TRUE`.

Ideally this would be done before our next release of nimble (we are about to release 1.2.0 this coming week, but for now we will have the error trap for using `RW_block` with discrete nodes be a warning).

**Comment by danielturek** [comment]
@weizhangstats

Looking at the `dbernppAC` custom distribution, is there any reason that it's registered as as a discrete distribution (using `discrete = TRUE`)?

Intuitively, and also looking at the code in `dbernppAC.R`, it seems like this should be a continuous distribution.

Looking through the other custom distributions, it seems the same discussion might apply to for `dbernppACmovement_exp`.

**Comment by weizhangstats** [comment]
Thanks for tagging me @danielturek. These are not discrete for sure. I am not sure why they were registered as discrete before. I will make the changes now.

**Comment by weizhangstats** [comment]
@paciorek @danielturek This is related to a couple of distributions and I corrected the registrations on the main branch directly

**Comment by danielturek** [comment]
Thanks @weizhangstats.  By my review, these were the only two distributions that were incorrect, which are both now fixed.  I'm closing this issue.

@paciorek Would it be necessary / helpful if this was pushed out quickly to CRAN?
